org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

mod_id=sophisticatedcore
mod_name=Sophisticated Core
mod_license=All Rights Reserved
mod_group_id=net.p3pp3rf1y
mod_version=1.3.77
sonar_project_key=sophisticatedcore:SophisticatedCore
github_package_url=https://maven.pkg.github.com/P3pp3rF1y/SophisticatedCore

#neoforge
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
neo_version=47.1.5
neo_version_range=[47.1,)
loader_version_range=[47,)

#publish
curseforge_id=618298
release_type=release
release_versions=1.20.1
modrinth_project_id=nmoqTijg

#deps
reliquary_version=[1.20.1-2.0.49,1.20.4)
jei_mc_version=1.20.1-forge
jei_version=15.20.0.133
jei_version_range=[15.20.0.106,)
emi_version=1.1.22+1.20.1
rei_version=12.1.785
cloth_config_version=11.1.136
architectury_version=9.2.14
create_mc_version=1.20.1
create_version=6.0.7-281
curios_version=5.7.0+1.20.1
balm_cf_file_id=4597440
crafting_tweaks_cf_file_id=4596466
item_borders_cf_file_id=4655513
iceberg_cf_file_id=4662780
prism_cf_file_id=4650325
chipped_cf_file_id=5077656
resourcefullib_cf_file_id=5070629
athena_cf_file_id=4764357
quark_cf_file_id=6427817
autoreglib_cf_file_id=3857246
trashslot_cf_file_id=6319121
botania_version=1.20.1-450-FORGE
patchouli_version=1.20.1-84.1-FORGE
ftb_chunks_version=2001.3.6
ftb_library_version=2001.2.10
accessories_version=1.0.0-beta.47+1.20.1
openpartiesandclaims_cf_file_id=6999169
parchment_version=2023.09.03-1.20.1
